### ISSUE TITLE
'updatealthingi' results in error

### ISSUE THREAD

**Issue by koddsson** [piratar/safetyvalve#5]
I just set up the project for the first time and the command `python manage.py updatealthingi` resulted in the following error:

```
☁  safetyvalve [master] python manage.py updatealthingi
Added session: 144
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/management/commands/updatealthingi.py", line 12, in handle
    update_issues()
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/utils.py", line 58, in update_issues
    issue.save()
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/models.py", line 42, in save
    althingi_source = Source.objects.get(name='althingi')
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
petition.models.DoesNotExist: Source matching query does not exist.
```

**Comment by jamesrobb** [comment]
Odd, I have just blown away my entire database, did a syncdb, and am able to use updatealthingi without issue. What branch are you using?

**Comment by koddsson** [comment]
`master`

**Comment by jamesrobb** [comment]
I know this sounds silly to ask, but have you done a syncdb? It seems
like it doesn't have the Source table in your local database from the
petition models.

//-- James Robb
//-- +354.666.0887 (Iceland/Ísland)

**Comment by koddsson** [comment]
I had already ran it, decided to give it another go and run `updatealthingi` again and now I got further:

```
☁  safetyvalve [master] python manage.py updatealthingi
Already have session: 144
Already have issue: 1 (fjárlög 2015)
- Added document: 1 (stjórnarfrumvarp)
- Added document: 638 (nefndarálit)
- Added document: 639 (breytingartillaga)
- Added document: 640 (breytingartillaga)
- Added document: 641 (breytingartillaga)
- Added document: 642 (breytingartillaga)
- Added document: 643 (breytingartillaga)
- Added document: 644 (breytingartillaga)
- Added document: 653 (nefndarálit)
- Added document: 654 (nefndarálit)
- Added document: 655 (nefndarálit)
- Added document: 656 (breytingartillaga)
- Added document: 665 (breytingartillaga)
- Added document: 711 (frumvarp eftir 2. umræðu)
- Added document: 756 (nefndarálit)
- Added document: 757 (breytingartillaga)
- Added document: 758 (breytingartillaga)
- Added document: 759 (breytingartillaga)
- Added document: 760 (breytingartillaga)
- Added document: 761 (breytingartillaga)
- Added document: 762 (breytingartillaga)
- Added document: 765 (breytingartillaga)
- Added document: 767 (nefndarálit)
- Added document: 768 (nefndarálit)
- Added document: 769 (nefndarálit)
- Added document: 770 (breytingartillaga)
- Added document: 771 (breytingartillaga)
- Added document: 772 (breytingartillaga)
- Added document: 776 (breytingartillaga)
- Added document: 785 (breytingartillaga)
- Added document: 787 (breytingartillaga)
- Added document: 797 (breytingartillaga)
- Added document: 798 (breytingartillaga)
- Added document: 801 (lög í heild)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/management/commands/updatealthingi.py", line 12, in handle
    update_issues()
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/utils.py", line 115, in update_issues
    main_doc.save()
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/models.py", line 73, in save
    petition = Petition.objects.get(external_id=external_id)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
petition.models.DoesNotExist: Petition matching query does not exist.
☁  safetyvalve [master]
```

**Comment by jamesrobb** [comment]
Interesting, not really sure what is going on. Funny how that goes
isn't it. All still works on my side.

What DB are you using? Maybe that is playing into it here.S

//-- James Robb
//-- +354.666.0887 (Iceland/Ísland)

**Comment by helgihg** [comment]
Try the 'dev' branch instead and let us know if that works. I highly
recommend emptying the database and starting from scratch, as well.

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by koddsson** [comment]
@helgihg I tried the dev branch but now it's a unknown command D:

```
☁  safetyvalve [dev] python manage.py updatealthingi
Unknown command: 'updatealthingi'
Type 'manage.py help' for usage.
```

**Comment by helgihg** [comment]
Try: ./manage.py update_althingi

Note that the command is simply a file under
althingi/management/commands/update_althingi.py :)

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by koddsson** [comment]
Ah! It has a underscore in the name in the `dev` branch! That worked except now I'm getting some `OperationalErrors`.

```
☁  safetyvalve [dev] python manage.py update_althingi
Already have session: 143
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/management/commands/update_althingi.py", line 12, in handle
    update_issues()
  File "/Users/koddsson/Repos/safetyvalve/safetyvalve/althingi/utils.py", line 60, in update_issues
    issue.save()
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
    using=using, raw=raw)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/koddsson/.virtualenvs/safetyvalve/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 451, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table althingi_issue has no column named final_vote_complete
```

**Comment by helgihg** [comment]
Try clearing the database entirely and running './manage.py syncdb' or
'./manage.py migrate' again with an entirely empty database.

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by koddsson** [comment]
Awesome! Thanks @helgihg @jamesrobb. I'm still getting some errors but at least I've got the `update_althingi` command working. :tada:

**Comment by helgihg** [comment]
Beautiful. :) Thanks for your efforts as well!

Kind regards,
Helgi Hrafn Gunnarsson
helgi@binary.is

**Comment by jamesrobb** [comment]
The thing that gets me though is that the master build still works for
me when doing a clean install.

Kristjan, would you mind telling me what DB you are using? Maybe it's a
DB issue for the master branch. I have been doing all my dev work and
testing with MySQL.

//-- James Robb
//-- +354.666.0887 (Iceland/Ísland)

**Comment by koddsson** [comment]
@jamesrobb sqlite

**Comment by jamesrobb** [comment]
Ah, I wonder if the problem lays in there, then. I am thinking maybe so, since that seems to be the obvious difference in our environments.

Admittedly the dev branch is a bit dirty, I'm not entirely sure where what the state of the code is like, so it would be worth keeping in mind that the master branch is likely the best set of code to use.

That being said though, I had been making changes way back when to the althingi module, so that is likely the point of divergence.
