### ISSUE TITLE
Suds not working with pip >= 3.2

### ISSUE THREAD

**Issue by busla** [piratar/safetyvalve#9]
OS: osx 10.11.1
Python: 3.4

`$ pip install -r requirements.txt`

``` python
Downloading/unpacking django==1.6.5 (from -r requirements.txt (line 1))
  Downloading Django-1.6.5-py2.py3-none-any.whl (6.7MB): 6.7MB downloaded
Downloading/unpacking beautifulsoup4 (from -r requirements.txt (line 2))
  Downloading beautifulsoup4-4.4.1-py3-none-any.whl (81kB): 81kB downloaded
Downloading/unpacking suds (from -r requirements.txt (line 3))
  Downloading suds-0.4.tar.gz (104kB): 104kB downloaded
  Running setup.py (path:/Users/nonni/Code/safetyvalve/venv/build/suds/setup.py) egg_info for package suds
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/nonni/Code/safetyvalve/venv/build/suds/setup.py", line 20, in <module>
        import suds
      File "/Users/nonni/Code/safetyvalve/venv/build/suds/suds/__init__.py", line 154, in <module>
        import client
    ImportError: No module named 'client'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/nonni/Code/safetyvalve/venv/build/suds/setup.py", line 20, in <module>

    import suds

  File "/Users/nonni/Code/safetyvalve/venv/build/suds/suds/__init__.py", line 154, in <module>

    import client

ImportError: No module named 'client'
```

**Comment by busla** [comment]
Using suds-jurko fixed it.
http://stackoverflow.com/questions/14973852/suds-install-error-no-module-named-client

**Comment by jamesrobb** [comment]
I assume this is resolved then?

**Comment by busla** [comment]
Yes.

**Comment by LaurentBerder** [comment]
Actually, it isn't:

Package `xmla` has `suds` in its dependencies.

```pip install xmla

Collecting xmla

  Using cached xmla-0.7.2.tar.gz

Requirement already satisfied: olap in c:\python35\lib\site-packages (from xmla)

Collecting suds (from xmla)

  Using cached suds-0.4.tar.gz

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "C:\Users\LAUREN~1\AppData\Local\Temp\pip-build-bkqbzt20\suds\setup.py", line 20, in <module>

        import suds

      File "C:\Users\LAUREN~1\AppData\Local\Temp\pip-build-bkqbzt20\suds\suds\__init__.py", line 154, in <module>

        import client

    ImportError: No module named 'client'
```

This happens even though I've already installed **`suds-jurko`**

**Comment by blazerpraveen** [comment]
@LaurentBerder i am facing same issue with xmla. Did u find any solution?

**Comment by LaurentBerder** [comment]
@blazerpraveen Nope, I dropped it. Sorry

**Comment by helgihg** [comment]
@LaurentBerder and @blazerpraveen , can you give some details on your environments? I've re-opened the issue.
